# Copyright (C) 2026 @FogWayfarer(https://github.com/FogWayfarer)<FogWayfarer@163.com>
# SPDX-License-Identifier: GPL-3.0-or-later
[package]
name = "block-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[[bin]]
name = "block-bench"
path = "src/main.rs"

[dependencies]
particlemc-framework-core = { path = "../particlemc-framework-core" }
