// Copyright (C) 2026 @FogWayfarer(https://github.com/FogWayfarer)<FogWayfarer@163.com>
// SPDX-License-Identifier: GPL-3.0-or-later
//! 伤害类型注册表与伤害值类型（T7，对应 spec R5）。
//!
//! [`DamageType`] 为数据驱动的注册条目（`resources/data/damage_types.toml`，
//! `[[entry]]` 数组）。`id` 为 0 基数据序位，对齐 Java autogenerated
//! `DamageTypes.java` 常量清单序位（即 Minecraft 数据注册表 `damage_type.json`
//! 的条目顺序）。[`DamageTypeRegistry`] 仿 [`AttributeRegistry`] 模式包装
//! [`Registry<DamageType>`]，提供 `from_toml_file` / `from_toml_str` /
//! `by_id` / `by_name`。
//!
//! 另承载三个伤害值类型：`EntityDamage`（实体直接伤害）、`PositionalDamage`
//! （位置伤害）、`EntityProjectileDamage`（弹道伤害），字段语义对齐 Java
//! `Damage` 的三个子类（source / sourcePosition / projectile）。
//!
//! 变更标识符：`complete-missing-subsystems`（T7）。

use std::path::Path;

use serde::Deserialize;

use crate::component::Damage;
use crate::resource::registries::{Registry, RegistryEntry, RegistryError};

/// 伤害类型定义（注册表条目）。
///
/// `scaling` 对齐 Java `DamageType.scaling()`：为字符串枚举
/// （`never` / `when_caused_by_living_non_player` / `always`），并非数值系数，
/// 故以 `String` 承载（任务草案中的 `f32` 与数据源及权威参考不符，已修正）。
#[derive(Clone, Debug, PartialEq, Deserialize)]
pub struct DamageType {
    /// 命名空间名称，如 `minecraft:fall`。
    pub name: String,
    /// 注册表 id（0 基数据序位，对齐 Java `DamageTypes` 常量清单）。
    pub id: u32,
    /// 体力消耗系数（Java `exhaustion`，float）。
    pub exhaustion: f32,
    /// 缩放模式（Java `scaling`，字符串枚举）。
    pub scaling: String,
}

impl RegistryEntry for DamageType {
    fn entry_name(&self) -> &str {
        &self.name
    }

    fn entry_id(&self) -> Option<u32> {
        Some(self.id)
    }
}

/// 伤害类型注册表（具名 `Resource`）。
///
/// 内部委托 [`Registry<DamageType>`] 承担「name ⇄ id」映射；条目由
/// `resources/data/damage_types.toml` 加载（`[[entry]]` 数组，`id` 为数据序位）。
#[derive(Default, Debug, Clone)]
pub struct DamageTypeRegistry {
    /// 底层注册表。
    inner: Registry<DamageType>,
}

impl DamageTypeRegistry {
    /// 从 TOML 文件加载伤害类型注册表。
    ///
    /// # 错误
    /// 路径不存在或条目无法反序列化时返回 [`RegistryError`]，由调用方决定
    /// 回退为空表。
    pub fn from_toml_file(path: &Path) -> Result<Self, RegistryError> {
        Ok(Self {
            inner: Registry::<DamageType>::from_toml_file(path)?,
        })
    }

    /// 从 JSON 文件加载伤害类型注册表。
    ///
    /// # 错误
    /// 路径不存在或条目无法反序列化时返回 [`RegistryError`]，由调用方决定
    /// 回退为空表。
    pub fn from_json_file(path: &Path) -> Result<Self, RegistryError> {
        Ok(Self {
            inner: Registry::<DamageType>::from_json_file(path)?,
        })
    }

    /// 从 TOML 文本加载伤害类型注册表（主要供单元测试使用）。
    pub fn from_toml_str(text: &str) -> Result<Self, RegistryError> {
        Ok(Self {
            inner: Registry::<DamageType>::from_toml_str(text)?,
        })
    }

    /// 按注册表 id 查询伤害类型。
    pub fn by_id(&self, id: u32) -> Option<&DamageType> {
        self.inner.get(id)
    }

    /// 按命名空间名称查询伤害类型。
    pub fn by_name(&self, name: &str) -> Option<&DamageType> {
        self.inner.get_id(name).and_then(|id| self.inner.get(id))
    }

    /// 遍历全部伤害类型（顺序不定）。
    pub fn all(&self) -> impl Iterator<Item = &DamageType> {
        self.inner.values()
    }

    /// 已注册伤害类型数量。
    pub fn len(&self) -> usize {
        self.inner.len()
    }

    /// 注册表是否为空。
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
}

/// 实体直接造成的伤害值类型（对齐 Java `EntityDamage`）。
///
/// `target` / `source` 均为 ECS 实体 id（`u32`）。
#[derive(Debug, Clone, PartialEq)]
pub struct EntityDamage {
    /// 受伤实体 id。
    pub target: u32,
    /// 攻击来源实体 id。
    pub source: u32,
    /// 伤害值（含类型与来源语义）。
    pub damage: Damage,
}

/// 位置伤害值类型（对齐 Java `PositionalDamage`）。
///
/// 用于岩浆、坠落、窒息等非实体环境来源，携带伤害来源坐标。
#[derive(Debug, Clone, PartialEq)]
pub struct PositionalDamage {
    /// 伤害来源坐标（`[x, y, z]`）。
    pub position: [f64; 3],
    /// 伤害值。
    pub damage: Damage,
}

/// 弹道伤害值类型（对齐 Java `EntityProjectileDamage`）。
///
/// `projectile` 为弹射物实体 id，`target` 为受伤实体 id。
#[derive(Debug, Clone, PartialEq)]
pub struct EntityProjectileDamage {
    /// 弹射物实体 id。
    pub projectile: u32,
    /// 受伤实体 id。
    pub target: u32,
    /// 伤害值。
    pub damage: Damage,
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    use crate::app::App;
    use crate::component::DamageSource;
    use crate::event::EntityDamage as EntityDamageEvent;
    use crate::prelude::{MessageReader, ResMut};

    #[test]
    fn registry_loads_from_toml_and_queries() {
        let toml = r#"
            [[entry]]
            name = "minecraft:fall"
            id = 29
            exhaustion = 0.0
            scaling = "when_caused_by_living_non_player"

            [[entry]]
            name = "minecraft:mob_attack"
            id = 30
            exhaustion = 0.1
            scaling = "when_caused_by_living_non_player"

            [[entry]]
            name = "minecraft:lava"
            id = 17
            exhaustion = 0.1
            scaling = "when_caused_by_living_non_player"
        "#;
        let registry = DamageTypeRegistry::from_toml_str(toml).unwrap();
        assert_eq!(registry.len(), 3);
        assert_eq!(registry.by_id(29).unwrap().name, "minecraft:fall");
        assert_eq!(registry.by_name("minecraft:mob_attack").unwrap().id, 30);
        assert_eq!(
            registry.by_name("minecraft:lava").unwrap().scaling,
            "when_caused_by_living_non_player"
        );
        assert!(registry.by_id(99).is_none());
        assert!(registry.by_name("minecraft:missing").is_none());
        assert!(!registry.is_empty());
    }

    #[test]
    fn registry_loads_real_data_file_with_aligned_ids() {
        // 真实注册数据：50 项，id 与 Java DamageTypes 常量清单序位一致（0 基）。
        let path =
            Path::new(env!("CARGO_MANIFEST_DIR")).join("../../resources/data/damage_types.json");
        let registry = DamageTypeRegistry::from_json_file(&path).unwrap();
        assert_eq!(registry.len(), 50);
        // 首尾与任务要求的 common 类型 id 核对。
        assert_eq!(registry.by_id(0).unwrap().name, "minecraft:wither");
        assert_eq!(registry.by_id(49).unwrap().name, "minecraft:cactus");
        assert_eq!(registry.by_name("minecraft:fall").unwrap().id, 29);
        assert_eq!(registry.by_name("minecraft:mob_attack").unwrap().id, 30);
        assert_eq!(registry.by_name("minecraft:mob_projectile").unwrap().id, 31);
        assert_eq!(registry.by_name("minecraft:drown").unwrap().id, 14);
        assert_eq!(registry.by_name("minecraft:lava").unwrap().id, 17);
        assert_eq!(registry.by_name("minecraft:starve").unwrap().id, 38);
        assert_eq!(registry.by_name("minecraft:explosion").unwrap().id, 44);
        assert_eq!(registry.by_name("minecraft:magic").unwrap().id, 43);
        assert_eq!(registry.by_name("minecraft:on_fire").unwrap().id, 4);
    }

    #[test]
    fn damage_value_types_carry_target_source_and_damage() {
        let entity = EntityDamage {
            target: 1,
            source: 2,
            damage: Damage::new(3.0),
        };
        assert_eq!(entity.target, 1);
        assert_eq!(entity.source, 2);
        assert_eq!(entity.damage.amount, 3.0);
        assert_eq!(entity.damage.source, DamageSource::Unknown);

        let positional = PositionalDamage {
            position: [1.0, 2.0, 3.0],
            damage: Damage::new(4.0),
        };
        assert_eq!(positional.position, [1.0, 2.0, 3.0]);
        assert_eq!(positional.damage.amount, 4.0);

        let projectile = EntityProjectileDamage {
            projectile: 5,
            target: 6,
            damage: Damage::new(7.0),
        };
        assert_eq!(projectile.projectile, 5);
        assert_eq!(projectile.target, 6);
        assert_eq!(projectile.damage.amount, 7.0);
    }

    #[test]
    fn entity_damage_message_is_delivered_after_app_update() {
        // 自研 ECS 消息时序：write_message 后跨两帧——第一次 update 置
        // Ready，第二次 update 的 First 才把消息推给 MessageReader。
        #[derive(Default)]
        struct Captured(Vec<EntityDamageEvent>);

        fn collect(reader: MessageReader<EntityDamageEvent>, mut out: ResMut<Captured>) {
            out.0.extend(reader.read().cloned());
        }

        let mut app = App::new();
        app.add_message::<EntityDamageEvent>()
            .init_resource::<Captured>()
            .add_systems(collect);

        let target = app.world_mut().spawn_empty().id();
        app.world_mut().write(EntityDamageEvent {
            entity: target,
            amount: 5.0,
            source: DamageSource::Entity(7),
            damage_type: None,
            cancelled: false,
        });
        app.update();
        app.update();

        let got = app.world().resource::<Captured>().unwrap().0.clone();
        assert_eq!(got.len(), 1);
        let event = got.first().unwrap();
        assert_eq!(event.entity, target);
        assert_eq!(event.amount, 5.0);
        assert_eq!(event.source, DamageSource::Entity(7));
        assert!(event.damage_type.is_none());
    }
}
